# Generated by Django 4.1.5 on 2023-01-10 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Acc_num', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('1', 'CURRENT'), ('2', 'SAVING')], max_length=10)),
                ('balance', models.BigIntegerField(default=0)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('amount', models.BigIntegerField(default=0)),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_acc', to='bankApp.account')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_acc', to='bankApp.account')),
            ],
        ),
    ]
