# Generated by Django 4.1.5 on 2023-01-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Acc_num',
            new_name='Account_number',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='Account_type',
        ),
    ]
