# Generated by Django 4.1.5 on 2023-01-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0002_rename_acc_num_account_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Account_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
